name: streamlit-env
channels:
  - conda-forge
  - apple
  - defaults
dependencies:
  - python=3.9
  - pip:
      - absl-py==1.4.0
      - aiohttp==3.8.3
      - aiosignal==1.3.1
      - alembic==1.9.1
      - altair==4.2.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.6.2
      - appnope==0.1.3
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - async-timeout==4.0.2
      - attrs==22.2.0
      - babel==2.11.0
      - backcall==0.2.0
      - beautifulsoup4==4.11.1
      - black==22.12.0
      - bleach==5.0.1
      - blinker==1.5
      - cachetools==5.2.1
      - cffi==1.15.1
      - charset-normalizer==2.1.1
      - click==8.1.3
      - cloudpickle==2.2.0
      - comm==0.1.2
      - commonmark==0.9.1
      - contourpy==1.0.6
      - cycler==0.11.0
      - databricks-cli==0.17.4
      - debugpy==1.6.5
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docker==6.0.1
      - entrypoints==0.4
      - exceptiongroup==1.1.0
      - executing==1.2.0
      - fastjsonschema==2.16.2
      - flask==2.2.2
      - fonttools==4.38.0
      - fqdn==1.5.1
      - frozenlist==1.3.3
      - fsspec==2022.11.0
      - gitdb==4.0.10
      - gitpython==3.1.30
      - google-auth==2.16.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.51.1
      - gunicorn==20.1.0
      - hydra-core==1.3.1
      - idna==3.4
      - importlib-metadata==5.2.0
      - iniconfig==2.0.0
      - ipykernel==6.20.1
      - ipython==8.8.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.4
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - json5==0.9.11
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==7.4.8
      - jupyter-console==6.4.4
      - jupyter-core==5.1.3
      - jupyter-events==0.6.2
      - jupyter-server==2.0.6
      - jupyter-server-terminals==0.4.4
      - jupyterlab==3.5.2
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.18.0
      - jupyterlab-widgets==3.0.5
      - kiwisolver==1.4.4
      - lightning-utilities==0.5.0
      - llvmlite==0.39.1
      - mako==1.2.4
      - markdown==3.4.1
      - markupsafe==2.1.1
      - matplotlib==3.6.3
      - matplotlib-inline==0.1.6
      - mistune==2.0.4
      - mlflow==2.1.1
      - multidict==6.0.4
      - mypy-extensions==0.4.3
      - nbclassic==0.4.8
      - nbclient==0.7.2
      - nbconvert==7.2.7
      - nbformat==5.7.3
      - nest-asyncio==1.5.6
      - notebook==6.5.2
      - notebook-shim==0.2.2
      - numba==0.56.4
      - numpy==1.23.5
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - packaging==22.0
      - pandas==1.5.2
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathspec==0.10.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.4.0
      - platformdirs==2.6.2
      - plotly==5.11.0
      - pluggy==1.0.0
      - progressbar==2.5
      - prometheus-client==0.15.0
      - prompt-toolkit==3.0.36
      - protobuf==3.20.1
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==10.0.1
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycparser==2.21
      - pydeck==0.8.0
      - pygments==2.14.0
      - pyjwt==2.6.0
      - pympler==1.0.1
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - pytest==7.2.0
      - python-dateutil==2.8.2
      - python-json-logger==2.0.4
      - pytorch-lightning==1.8.6
      - pytz==2022.7
      - pytz-deprecation-shim==0.1.0.post0
      - pyyaml==6.0
      - pyzmq==25.0.0
      - qtconsole==5.4.0
      - qtpy==2.3.0
      - querystring-parser==1.2.4
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.0.1
      - rsa==4.9
      - scikit-learn==1.2.0
      - scipy==1.10.0
      - seaborn==0.12.2
      - semver==2.13.0
      - send2trash==1.8.0
      - shap==0.41.0
      - six==1.16.0
      - slicer==0.0.7
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.3.2.post1
      - sqlalchemy==1.4.46
      - sqlparse==0.4.3
      - stack-data==0.6.2
      - streamlit==1.16.0
      - tabulate==0.9.0
      - tenacity==8.1.0
      - tensorboard==2.11.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.5.1
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tinycss2==1.2.1
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.0
      - torch==1.13.1
      - torchmetrics==0.11.0
      - torchvision==0.14.1
      - tornado==6.2
      - tqdm==4.64.1
      - traitlets==5.8.1
      - typing-extensions==4.4.0
      - tzdata==2022.7
      - tzlocal==4.2
      - uri-template==1.2.0
      - urllib3==1.26.14
      - validators==0.20.0
      - wcwidth==0.2.5
      - webcolors==1.12
      - webencodings==0.5.1
      - websocket-client==1.4.2
      - werkzeug==2.2.2
      - widgetsnbextension==4.0.5
      - yarl==1.8.2
      - zipp==3.11.0
